# Generated by Django 4.2 on 2024-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('P', 'Planta'), ('A', 'Agua'), ('F', 'Fuego'), ('T', 'Tierra')], max_length=30),
        ),
    ]
